### ISSUE TITLE
Datalayer keeps looping

### ISSUE THREAD

**Issue by joakim973** [cakmakumut/app-web-ecommerce#1]
Have tested this Custom Template on one site and on the checkout-pages the DL keeps looping forever. On the other events it works fine, I do not see what I have done differently on the checkout-event.

<img width="422" alt="Screenshot at May 20 13-18-42" src="https://user-images.githubusercontent.com/59467421/82440578-dce82b00-9a9c-11ea-9177-3b9d2dceb1d8.png">

**Comment by cakmakumut** [comment]
Hi @joakim973, 
I tested on different websites, but I did not see the problem you mentioned. If you can share the GTM preview link with me, I can examine it in more detail.
